### ISSUE TITLE
KeyError: 'isListed' not found in service['metadata']['curation']

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/aquarius#150]
## Expected Behavior

Aquarius listing to return a list of assets found based on a search text.

## Current Behavior

Search for assets from squid-py fails, with an html error

> raise Exception(f'Unable to search for DDO: {response.content}')

## Failure Information (for bugs)

squid-py failure on line
```python
    # search for assets
    asset_ddo = ocean.assets.search('Ocean protocol')[0]
```

## Step to Reproduce the problem
I'm trying to run the demo code from the README.md on squid-py repo, here is a sample of my 'test.py'
```python
    ConfigProvider.set_config(Config('test_config.ini'))
    # Make a new instance of Ocean
    ocean = Ocean()
    config = ConfigProvider.get_config()
    # make account instance, assuming the ethereum account and password are set 
    # in the config file `config.ini`
    account = ocean.accounts.list()[0]
    # or 
    account = Account(config.parity_address, config.parity_password)

    # PUBLISHER
    # Let's start by registering an asset in the Ocean network
    metadata = Metadata.get_example()

    # purchase and service endpoints require `brizo.url` is set in the config file
    # or passed to Ocean instance in the config_dict.
    # define the services to include in the new asset DDO

    ddo = ocean.assets.create(metadata, account)

    # Now we have an asset registered, we can verify it exists by resolving the did
    _ddo = ocean.assets.resolve(ddo.did)
    # ddo and _ddo should be identical

    # CONSUMER
    # search for assets
    asset_ddo = ocean.assets.search('Ocean protocol')[0]
    # Need some ocean tokens to be able to purchase assets
```
## Specifications

running latest barge
```bash
./start_ocean.sh --no-pleuston --local-spree-node --latest
```
squid-py 0.4.4 or branch/develop, both versions get the same error

## Failure Logs

> aquarius_1                   | 2019-02-26 05:54:12 ad54e2f71448 flask.app[9] ERROR Exception on /api/v1/aquarius/assets/ddo/query [GET]
> aquarius_1                   | Traceback (most recent call last):
> aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> aquarius_1                   |     response = self.full_dispatch_request()
> aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> aquarius_1                   |     rv = self.handle_user_exception(e)
> aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
> aquarius_1                   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
> aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> aquarius_1                   |     reraise(exc_type, exc_value, tb)
> aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> aquarius_1                   |     raise value
> aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> aquarius_1                   |     rv = self.dispatch_request()
> aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> aquarius_1                   |     return self.view_functions[rule.endpoint](**req.view_args)
> aquarius_1                   |   File "/aquarius/aquarius/app/assets.py", line 546, in query_text
> aquarius_1                   |     query_result = dao.query(search_model)
> aquarius_1                   |   File "/aquarius/aquarius/app/dao.py", line 64, in query
> aquarius_1                   |     if self.is_listed(f['service']):
> aquarius_1                   |   File "/aquarius/aquarius/app/dao.py", line 72, in is_listed
> aquarius_1                   |     return service['metadata']['curation']['isListed']
> aquarius_1                   | KeyError: 'isListed'
>

**Comment by billbsing** [comment]
Found out what it is , after reloading Docker images again it works. 
So I was running an older version of aquarius previously on the same mongo db, and there where records in the mongo db that did not have 'isListed' field
