### ISSUE TITLE
Failure in search query

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/aquarius#154]
Aquarius is failing running in barge using the last version when you send a search query:

```
curl -X GET "http://0.0.0.0:5000/api/v1/aquarius/assets/ddo/query?text=Weather&sort=%5Bobject%20Object%5D&offset=100" -H "accept: application/json"
```

Error:
```

500Undocumented | Error: INTERNAL SERVER ERRORResponse body<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
-- | --


```

In the docker logs:
```
aquarius_1                   | 2019-03-05 12:04:59 7a3379aed6bd flask.app[152] ERROR Exception on /api/v1/aquarius/assets/ddo/query [GET]
aquarius_1                   | Traceback (most recent call last):
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
aquarius_1                   |     response = self.full_dispatch_request()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
aquarius_1                   |     rv = self.handle_user_exception(e)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
aquarius_1                   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
aquarius_1                   |     reraise(exc_type, exc_value, tb)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
aquarius_1                   |     raise value
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
aquarius_1                   |     rv = self.dispatch_request()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
aquarius_1                   |     return self.view_functions[rule.endpoint](**req.view_args)
aquarius_1                   |   File "/aquarius/aquarius/app/assets.py", line 543, in query_text
aquarius_1                   |     data.get('sort', None)),
aquarius_1                   |   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
aquarius_1                   |     return _default_decoder.decode(s)
aquarius_1                   |   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
aquarius_1                   |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
aquarius_1                   |   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
aquarius_1                   |     raise JSONDecodeError("Expecting value", s, err.value) from None
aquarius_1                   | json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Comment by kremalicious** [comment]
the `sort=%5Bobject%20Object%5D` in the search query is making it fail so the search query is malformed.

Correct form throwing no error would be:

```
curl -X GET \
  "http://0.0.0.0:5000/api/v1/aquarius/assets/ddo/query?text=Weather&sort%3D%7BdatePublished%3A1%7D&offset=100" \
  -H "accept: application/json"
```
