### ISSUE TITLE
Handle decrypt errors

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#723]
```
2022-03-02 16:09:45,214 - aquarius.events.events_monitor - DEBUG - Metadata monitor (chain: 4)>>>> from_block:10259306, current_block:10259306 <<<<
2022-03-02 16:09:47,308 - aquarius.events.events_monitor - DEBUG - Metadata monitor (chain: 4)>>>> from_block:10259306, current_block:10259307 <<<<
2022-03-02 16:09:47,493 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: Provider exception on decrypt DDO: b'{"context":{"chainId":4,"decrypterAddress":"0xF41681F0BE4A914d447d7A94C91906E74A6561D0","nonce":"1646237387.441213","signature":"0x4fed3c2de20aa62b6fc04292dbab8a2b45ab9256ee0fb6ae314fef5a4e31885a23a44f7e9843901386239266c16f8843e3b3ab0e3ea393ae480ed462722315e81b","transactionId":"0x3e5b31a87d0faf89f425903b29a5867c2c1075ada78ff19b22f4d62d80b4607a"},"error":"(\'Connection aborted.\', ConnectionResetError(104, \'Connection reset by peer\'))"}\n'
event=AttributeDict({'address': '0x5569Db76C312Bd76864b635c6c78274b3bd69B7F', 'blockHash': HexBytes('0x65b351b31709134adbb12f3ee3e42cd87887f8bcc2452fff0928a17c2e11fc4e'), 'blockNumber': 10259307, 'data': '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000180e97f4f3463f06e27cc57234751704f142f9321a6118cbc394cd59e354e5c0a1500000000000000000000000000000000000000000000000000000000621f96c500000000000000000000000000000000000000000000000000000000009c8b6b000000000000000000000000000000000000000000000000000000000000002d68747470733a2f2f76342e70726f76696465722e72696e6b6562792e6f6365616e70726f746f636f6c2e636f6d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000102000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000563040f5c1f45ec64d0feba669a355c9c45209eba2f4df67adb22ee60574b95269b42c4d2c3e2b052447622e41b733f8232403e3536c4f9462e5bd2ed546df74cfa87982ad79586b076b7e0a2ef98863ed29f253927fbefb09608ed7892365332566dc3743faa1172d3dc1f7e2672cc41029c3ea421b6feb71ebeee8b9dc2918e4f3dc0af12a392d4de4227a6ddcf4942e1e3c87ca7bb63e74b9855b7775947d1e56d4b221db0ec5dfe7b0f59d19fcbae4af6be587f4abb59f711855d3f382cf2cabc0c9137c7ddb8aeee353d27051655596ef80a47edf2f642695369b2770fb336652452f1ff5794860b85e7d4fff455d469753d51bb4aa3930a5ca16a7b2b307563425b45564b68ef4408cedfef75c521ae28fc03efdd1b53259be291bfdeacdb3245929e086724fc786d0b9bbaed7de1b80550ce3e93bed04fd2250ba695cef07012c5c710acb5ca94a3fb9f15e321e9384a4cdeabc6b6123bbc6c955d99411730cba9da45363be0bf5f184dfcf4588a69af1484fcdd811f34a48856ba846dd75c03f0f8f1eaec97c6fab694d0b427b16789b3704a46ece22442d054297b943561b0ed2f28ea45818e2d822a1a9813eb7164c7c92532e68bc3367a257c853c798bcc7e666020a6ca34dcff032d65489b231da4f94742bd7007d70cbcfe29839a72dec1f667b1aa0e2bab823be3fc60e8e049e34d0c8f1840b1a60520adfdb423039687bb10b198866d6ffae9ea084d4ed3f1ff9851b9d65112e6d232e2f19695e5aed514c3550a6bca8064abcd5b6c35f2633922d0ace506d73aca06341033ea27ccfc9de74be41a6166221a1124c3a5e223c9006f70b44820408170b0a2d7872a31a3f84c8946ba5a7521e4f924128c4c06edcd2f12fbcb70fc344ee16510fd715269c94e4d5e560b65ff272eac911ca59794b875ae0d03cf42165b56a025765a0e7406438a0b538f8e7183d41ae0feb46b0aa944c99f27377b8f201175ce930f351b273e61ba3db916c8fc43f97a06c283efb5ce3bdc0e1c8b9ab47230b2a4048e74f5101b5f1acd9937f89a0d6b9ffb7d12641973b81f71b3dfbc05e21053238aac1cc6f90b31c6d3b20612d5e2291fe15b5b4fe2e33ea5e660a7fda0fe3cb67db4b5dc3850816024bfc72c6b4539eff3c45396975983fdee98bed403400427d7f26789f86f44e1a66039246a2b324c830690489d404bbebceee93758be864b4b0f5e6aae63fe546ea50de8fd84da684111ed91ce5c1c50a273a7b018092e7f1646ef0930cc16211ecd39d101816eaaf1c21d87a0f1f020d31ed886ffba8d73fcbd9451b205efd9684aa693d01147ea96164324cd40327c15c9f45350a3c5dc5dd5a9bdba7bc0242fabcd27eaaf487953d3975c9e264fb1f4913f4eee61a8235815c1c836c80455fbfc6aca7224d7f32cd756f9158d42b2db4482ca57cf33d1e076eb3bc03de7be15d715edc83ad39f2dd85ec74c8e79e26bd48967b2c12d779833bf191b6b016b5187a8e7239e0411e5c9a220fcd65384475a847f7f2bf546f9e347b7ec87660136be83ed338c751ba4b974f5ca60d0b1fb0e0c3cfff1f196eef12fe22db1290f35b51971d7028d2a45809fab793d03cd71ffbb35129f3714df9d8acbf3500cdd2b7bd295e64eb8c9e8894f69231ab8fd203013538ba38e11bf2171231a252c1833da3da40179a531017c2c29255aca1a3517490796d353613b1c648d9ecc1ff08d96f76d22bf5ce8ca1a2b6ed75f820ec057de85b3d5aece08f68218c880c242368ca9fcc53dcaeff6b122f8b151be0627379acd252a3382a93e6b16b685fe638253ef9b2797a9cd1f36d36a29cd8a2b01e72f876bb9614984fa5a96680b9e7bb67faef994da5a797d23333ae0ac4d0989e0934b717dd7848c16808c585f8258f62887f056a2ac0e00509699013a1482c42deca2c16e2695a97b0000000000000000000000000000000000000000000000000000000000', 'logIndex': 117, 'removed': False, 'topics': [HexBytes('0x5463569dcc320958360074a9ab27e809e8a6942c394fb151d139b5f7b4ecb1bd'), HexBytes('0x000000000000000000000000bee7e78668fd81d02d33fc41aad70aaa815b0916')], 'transactionHash': HexBytes('0x3e5b31a87d0faf89f425903b29a5867c2c1075ada78ff19b22f4d62d80b4607a'), 'transactionIndex': 55})
Traceback (most recent call last):
  File "/aquarius/aquarius/events/events_monitor.py", line 233, in handle_regular_event_processor
    event_processor.process()
  File "/aquarius/aquarius/events/processors.py", line 209, in process
    asset = decrypt_ddo(
  File "/aquarius/aquarius/events/decryptor.py", line 37, in decrypt_ddo
    raise Exception(f"Provider exception on decrypt DDO: {response.content}")
Exception: Provider exception on decrypt DDO: b'{"context":{"chainId":4,"decrypterAddress":"0xF41681F0BE4A914d447d7A94C91906E74A6561D0","nonce":"1646237387.441213","signature":"0x4fed3c2de20aa62b6fc04292dbab8a2b45ab9256ee0fb6ae314fef5a4e31885a23a44f7e9843901386239266c16f8843e3b3ab0e3ea393ae480ed462722315e81b","transactionId":"0x3e5b31a87d0faf89f425903b29a5867c2c1075ada78ff19b22f4d62d80b4607a"},"error":"(\'Connection aborted.\', ConnectionResetError(104, \'Connection reset by peer\'))"}\n'
```

We should really catch all errors

**Comment by mariacarmina** [comment]
Can we tackle this issue in #723 since it's related to that problem?
